/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.datasqlserver;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ifajr
 */
public class Supplier extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    
  
    public Supplier() {
        initComponents();
        
//        //View Table Detail Supplier
//        tbl_det_supplier();
//        //View Table Supplier
//        tbl_supplier();
//        //View Table Product
//        tbl_product();
        load_table();
        txtiddet.setVisible(false);
        txtIdSp.setVisible(false);
        txtNameSp.setEnabled(true);
        txtNameProduct.setEnabled(false);
        txtStockPr.setEnabled(false);
        jButton6.setEnabled(false);
        jButton5.setEnabled(false);
        jButton4.setEnabled(false);
        jButton9.setEnabled(false);

    }
    private void load_table(){
          //View Table Detail Supplier
        tbl_det_supplier();
        //View Table Supplier
        tbl_supplier();
        //View Table Product
        tbl_product();
    }
//    
//    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
//    String url = "jdbc:sqlserver://localhost\\HUUH:1433;databaseName=db_vending_machine;encrypt=true;trustServerCertificate=true;";
//    String username = "admin";
//    String password = "admin";
    
     String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url = "jdbc:sqlserver://localhost\\HUUH:1433;databaseName=db_vending_machine;encrypt=true;trustServerCertificate=true;";
    String username = "admin";
    String password = "admin";
    
    
    Statement st;
    ResultSet rs;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_supplier = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_det = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNameitems = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        txtPriceSp = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_product = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        txtiddet = new javax.swing.JTextField();
        txtNameSp = new javax.swing.JTextField();
        txtNameProduct = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtStockPr = new javax.swing.JTextField();
        txtPricePr = new javax.swing.JTextField();
        txtIdSp = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "id det supplier", "Items", "Quantity", "Price"
            }
        ));
        table_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_supplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_supplier);

        table_det.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Phone", "Address"
            }
        ));
        table_det.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_detMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_det);

        jButton1.setText("Add Supplier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Name Supplier");

        jLabel2.setText("Name Items");

        jLabel3.setText("Quantity");

        jLabel4.setText("Price");

        txtNameitems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameitemsActionPerformed(evt);
            }
        });

        txtPriceSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceSpActionPerformed(evt);
            }
        });

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Edit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Adding Stock");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Clear");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel5.setText("Display In User");

        table_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Product", "Name Items", "Stock", "Price"
            }
        ));
        table_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_productMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_product);

        jButton8.setText("Add Items To User");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        txtiddet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiddetActionPerformed(evt);
            }
        });

        txtNameSp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNameSp.setToolTipText("");

        txtNameProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameProductActionPerformed(evt);
            }
        });

        jLabel6.setText("Items");

        jLabel7.setText("Stock");

        jLabel8.setText("Price");

        txtStockPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockPrActionPerformed(evt);
            }
        });

        jButton9.setText("Get Data");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNameSp, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNameitems, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtQty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPriceSp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtiddet, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(jButton7))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton9)))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtStockPr, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPricePr, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIdSp, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(36, 36, 36))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNameSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jButton6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(txtNameitems, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPriceSp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtiddet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton5)
                                    .addComponent(jButton7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4)
                                    .addComponent(jButton9))
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(txtIdSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtStockPr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtPricePr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jButton8))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jButton7.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_det_supplier(){
        DefaultTableModel tbl_det_sp = new DefaultTableModel();
        tbl_det_sp.addColumn("id");
        tbl_det_sp.addColumn("Name");
        tbl_det_sp.addColumn("Phone");
        tbl_det_sp.addColumn("Address");
        table_det.setModel(tbl_det_sp);

        try{
                    Class.forName(driver);

            Connection con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            rs = st.executeQuery("select * from dbo.tbl_det_supplier");
            while(rs.next()){
                tbl_det_sp.addRow(new Object[]{
                    rs.getString("id_det_supplier"),
                    rs.getString("name_supplier"),
                    rs.getString("tlp"),
                    rs.getString("address")
                
                });
               
            }
            table_det.setModel(tbl_det_sp);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "data gagal");
        }
    }
    
    
     private void tbl_supplier(){
        DefaultTableModel tbl_sp = new DefaultTableModel();
        tbl_sp.addColumn("id");
        tbl_sp.addColumn("id det supplier");
        tbl_sp.addColumn("Items");
        tbl_sp.addColumn("Quantity");
        tbl_sp.addColumn("Price");
        table_supplier.setModel(tbl_sp);

        try{
                    Class.forName(driver);

            Connection con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            rs = st.executeQuery("select * from dbo.tbl_supplier");
            while(rs.next()){
                tbl_sp.addRow(new Object[]{
                    rs.getString("id_supplier"),
                    rs.getString("id_det_supplier"),
                    rs.getString("name_product"),
                    rs.getString("total_product"),
                    rs.getString("price")

                
                });
               
            }
            table_supplier.setModel(tbl_sp);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "data gagal");
        }
    }
     
     //view Table Product
    
     private void tbl_product(){
        DefaultTableModel tbl_pr = new DefaultTableModel();
        tbl_pr.addColumn("Id Product");
        tbl_pr.addColumn("Name Items");
        tbl_pr.addColumn("Stock");
        tbl_pr.addColumn("Price");
        table_product.setModel(tbl_pr);

        try{
                    Class.forName(driver);

            Connection con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            rs = st.executeQuery("select * from dbo.tbl_product pr join dbo.tbl_supplier sp on pr.id_supplier = sp.id_supplier");
            while(rs.next()){
                tbl_pr.addRow(new Object[]{
                    rs.getString("id_product"),
                    rs.getString("name_product"),
                    rs.getString("stock"),
                    rs.getString("price")

                
                });
               
            }
            table_product.setModel(tbl_pr);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "data gagal");
        }
    }
    
    private void txtPriceSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceSpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceSpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        new addsuplier().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void table_detMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_detMouseClicked
        // TODO add your handling code here:
        int row = table_det.getSelectedRow();
        DefaultTableModel   model_det = (DefaultTableModel)table_det.getModel();
        txtiddet.setText(model_det.getValueAt(row, 0).toString());
        txtNameSp.setText(model_det.getValueAt(row, 1).toString());
    }//GEN-LAST:event_table_detMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          try {
            
             Class.forName(driver);
            Connection con = DriverManager.getConnection(url,username,password);
            String sql ="insert into dbo.tbl_supplier (id_det_supplier, name_product, total_product, price) values ('"+txtiddet.getText()+"','"+txtNameitems.getText()+"','"+txtQty.getText()+"','"+txtPriceSp.getText()+"')";

            st = con.createStatement();
            st.execute(sql);
            refresh_supplier();
            JOptionPane.showMessageDialog(this, "insert Product Supplier successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    private void table_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_supplierMouseClicked
        // TODO add your handling code here
        jButton3.setEnabled(false);
        jButton9.setEnabled(true);
        
        int row = table_supplier.getSelectedRow();
        DefaultTableModel   model_det = (DefaultTableModel)table_supplier.getModel();

        if (getdata){
        // edit code
        String Sharga = (String) model_det.getValueAt(row, 4);
        String Koharga = Sharga.replace(".","");
        String Nolharga = Koharga.substring(0, Koharga.length()-4);
        txtNameitems.setText(model_det.getValueAt(row, 2).toString());
        txtQty.setText(model_det.getValueAt(row, 3).toString());
        txtIdSp.setText(model_det.getValueAt(row, 0).toString());

        txtPriceSp.setText(Nolharga);
        
        getdata = false;
        }
        else{
        txtIdSp.setText(model_det.getValueAt(row, 0).toString());
        txtNameProduct.setText(model_det.getValueAt(row, 2).toString());
        txtStockPr.setText(model_det.getValueAt(row, 3).toString());
        }
    

        

    }//GEN-LAST:event_table_supplierMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
           try {
            
             Class.forName(driver);
             String Sstock, Sprice, Sid_sp;
             Sstock = txtStockPr.getText();
             int stock = Integer.parseInt(Sstock);
             Sid_sp = txtIdSp.getText();
             int id_sp = Integer.parseInt(Sid_sp);
             
             Sprice = txtStockPr.getText();
             int price = Integer.parseInt(Sprice);
             
            Connection con = DriverManager.getConnection(url,username,password);
            String sql ="insert into dbo.tbl_product (id_supplier, stock, price) values (' "+id_sp+" ',' "+stock+" ',' "+price+" ')";

            st = con.createStatement();
            st.execute(sql);
            
//            rs =st.executeQuery("select total_product from dbo.tbl_supplier where id_supplier = ' "+id_sp+" ' ");
//            if(rs.next()){
//                String Sstock_old = rs.getString("total_product");
//                int stock_old = Integer.parseInt(Sstock_old);
//                  int new_stock = stock_old - stock;
//            
//            
//            
//            String update ="update dbo.tbl_supplier set total_product = ' "+new_stock+" '  where  id_supplier = ' "+id_sp+" ' ";
//            st = con.createStatement();
//            st.execute(update);
//            
//            }
          
            tbl_product();
            
            JOptionPane.showMessageDialog(this, "insert Product Supplier successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void table_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_productMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_productMouseClicked

    private void txtNameProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameProductActionPerformed

    private void txtStockPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockPrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockPrActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

//        jButton4.setEnabled(false);
//        jButton3.setEnabled(false);
        
 
         try {
            String id_sp =  txtIdSp.getText();
            String name = txtNameitems.getText();
            String stock = txtQty.getText();
            String price = txtPriceSp.getText();
             Class.forName(driver);
            Connection con = DriverManager.getConnection(url,username,password);
            String sql ="update dbo.tbl_supplier set name_product ='"+name+"' , total_product = '"+stock+"' , price = '"+price+"'  where id_supplier =  '"+id_sp+"'";
                        refresh_supplier();
                        
            st = con.createStatement();
            st.execute(sql);
                        load_table();
                        JOptionPane.showMessageDialog(this, "Update successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
//        isEdit = false;
      
        refresh_supplier();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton5.setEnabled(false);
        jButton3.setEnabled(false);
        String id_sp =  txtIdSp.getText();
         try {
            
             Class.forName(driver);
            Connection con = DriverManager.getConnection(url,username,password);
            String sql ="delete from dbo.tbl_supplier where id_supplier =  '"+id_sp+"'";
            
            st = con.createStatement();
            st.execute(sql);
            refresh_supplier();
            JOptionPane.showMessageDialog(this, "Delete successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtNameitemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameitemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameitemsActionPerformed
    private boolean adding = false;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code 
        
        adding = true;
        txtNameitems.setEnabled(false);
        txtPriceSp.setEnabled(false);
        String Sid_sp = txtIdSp.getText();
        int id_sp = Integer.parseInt(Sid_sp);
        String Sadd_stock = txtQty.getText();
        int add_stock = Integer.parseInt(Sadd_stock);
        
          try {
            
             Class.forName(driver);
            Connection con = DriverManager.getConnection(url,username,password);
                     st = con.createStatement();
                    rs = st.executeQuery("select * from dbo.tbl_supplier where id_supplier =  '"+id_sp+"'");
                    String  stock_old=rs.getString("total_product");
            int stocknow = Integer.parseInt(stock_old);
            int new_stock = add_stock + stocknow;
            
            String update ="update dbo.tbl_supplier set total_product = '"+new_stock+"'  where id_supplier =  '"+id_sp+"'";

            st = con.createStatement();
            st.execute(update);
            
            
            
            refresh_supplier();
            JOptionPane.showMessageDialog(this, "Update successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    private boolean getdata = false;
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here
            getdata = true;
           jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        
      
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtiddetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiddetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtiddetActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       new VendingMachine().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void refresh_supplier(){
        jButton3.setEnabled(true);
        jButton9.setEnabled(false);
        jButton5.setEnabled(false);
        jButton4.setEnabled(false);
        jButton6.setEnabled(false);
        txtNameSp.setText("");
        txtIdSp.setText("");
        txtNameitems.setText("");
        txtQty.setText("");
        txtPriceSp.setText("");
        txtiddet.setText("");
        load_table();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table_det;
    private javax.swing.JTable table_product;
    private javax.swing.JTable table_supplier;
    private javax.swing.JTextField txtIdSp;
    private javax.swing.JTextField txtNameProduct;
    private javax.swing.JTextField txtNameSp;
    private javax.swing.JTextField txtNameitems;
    private javax.swing.JTextField txtPricePr;
    private javax.swing.JTextField txtPriceSp;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtStockPr;
    private javax.swing.JTextField txtiddet;
    // End of variables declaration//GEN-END:variables
}
